name = "archi-inspiration"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Custom domain
routes = [
  { pattern = "archi-match.com", custom_domain = true },
  { pattern = "www.archi-match.com", custom_domain = true }
]

# [[d1_databases]]
# binding = "DB"
# database_name = "archi-match-db"
# database_id = "d74d4c80-0af7-4a7c-8e57-4ea6d8668040"
